image:
  name: 845945358136.dkr.ecr.eu-west-1.amazonaws.com/cloud-deploy-ci:2018-05-14

stages:
  - unit-tests

services:
  - mongo:2.6

pipelines:
  stage: unit-tests
  tags:
    - default
  script:
    - ./ci-pipelines.sh "${CI_COMMIT_REF_NAME}"
