#!/bin/bash
set -x
S3_BUCKET={{ bucket_s3 }}
S3_REGION={{ bucket_region }}
NOTIFICATION_ENDPOINT={{ notification_endpoint }}

EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"

AWS_BIN=$(which aws)
if [ $? -ne 0 ]; then
    AWS_BIN='/usr/local/bin/aws'
fi

LOGDIR=/var/log/ghost/
STAGE2_PATH=/var/lib/ghost/stage2_bootstrap
STAGE2_PATH_LOG=${LOGDIR}stage2_bootstrap.log

if [ ! -d /var/lib/ghost ]; then
    mkdir /var/lib/ghost
fi

if [ ! -d ${LOGDIR} ]; then
    mkdir ${LOGDIR}
fi

function download_stage2() {
    $AWS_BIN s3 cp s3://$S3_BUCKET/ghost/stage2 $STAGE2_PATH --region "$S3_REGION"
    chmod +x $STAGE2_PATH
}

function execute_stage2() {
	NOTIFICATION_ENDPOINT=$NOTIFICATION_ENDPOINT $STAGE2_PATH > $STAGE2_PATH_LOG 2>&1
}

download_stage2
execute_stage2
