#!/bin/bash
set -x
S3_BUCKET={{ bucket_s3 }}

EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"

function download_stage2() {
    /usr/local/bin/aws s3 cp s3://$S3_BUCKET/ghost/stage2 /tmp/stage2  --region "$EC2_REGION"
    chmod +x /tmp/stage2
}

function execute_stage2() {
	/tmp/stage2 > /tmp/log_bootstrap_stage2.txt
}

download_stage2
execute_stage2